project_name: helm-schema-gen

env:
  - GO111MODULE=on

# Prevents parallel builds from stepping on each others toes downloading modules
before:
  hooks:
  - go mod tidy

gomod:
  proxy: true

sboms:
- artifacts: binary

builds:
  - binary: helm-schema-gen-{{ .Os }}-{{ .Arch }}
    no_unique_dist_dir: true
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - arm
    ignore:
      - goos: windows
        goarch: arm

archives:
- format: binary
  name_template: "{{ .Binary }}"
  allow_different_binary_count: true

signs:
- cmd: cosign
  env:
  - COSIGN_EXPERIMENTAL=true
  certificate: '${artifact}.pem'
  signature: '${artifact}.sig'
  args:
    - sign-blob
    - '--output-certificate=${certificate}'
    - '--output-signature=${signature}'
    - '${artifact}'
  artifacts: binary
  output: true

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: SNAPSHOT-{{ .ShortCommit }}

release:
  prerelease: allow # remove this when we start publishing non-prerelease or set to auto
  draft: true # allow for manual edits
  github:
    owner: cpanato
    name: helm-schema-gen
