name: Release

on:
  push:
    tags:
      - "*"

permissions:
  contents: write # needed to write releases
  id-token: write # needed for keyless signing

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check plugin version matches tag
        run: |
          plugin_version="$(grep version plugin.yaml  | cut -d '"' -f 2)"
          version_line="$(grep -n "${plugin_version}" plugin.yaml | cut -d: -f1)"
          tag=${GITHUB_REF##*/}
          [ "${tag##v}" != "${plugin_version}" ] && {
            error_title="Version was not updated in plugin.yaml"
            error_message="Got: ${plugin_version}, Require: ${tag##v} for ${tag}"
            echo "::error file=plugin.yaml,line=${version_line},endLine=${version_line},title=${error_title}::${error_message}" >&2
            exit 1
          }

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
          check-latest: true

      - uses: sigstore/cosign-installer@ced07f21fb1da67979f539bbc6304c16c0677e76 # v2.7.0
      - uses: anchore/sbom-action/download-syft@b5042e9d19d8b32849779bfe17673ff84aec702d # v0.11.0

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COSIGN_EXPERIMENTAL: true
